Core: New - Add compatibility tag headers
pojome/elementor-hello-world pull request #19
Opened 2020-12-01 08:48 UTC by Nevoss

2020-12-01 14:05 UTC, matipojo requested changes

2020-12-01 14:05 UTC, matipojo commented on elementor-hello-world.php
> + * Elementor tested up to: 3.0.0
Test it!

2020-12-01 15:48 UTC, Nevoss commented on elementor-hello-world.php
> + * Elementor tested up to: 3.0.0
Checked and it works. 👍

2020-12-06 13:56 UTC, matipojo approved these changes

2020-12-06 15:05 UTC, merged